stages:
  - build-image
  - stop-old-deploy
  - deploy
  - migrate

build-image:
  stage: build-image
  script:
    - docker build --no-cache -t pgms-backend-$CI_COMMIT_REF_NAME .
  
# test:
#   script:
#     - docker run -itd --rm pgms-backend:latest npm run test

delete-old-container:
  stage: stop-old-deploy
  script:
    - docker rm -f pgms-backend || true

deploy:
  stage: deploy
  script:
    - docker run -itd --restart=always -p 5001:5001 --name pgms-backend pgms-backend:latest
  only:
    - master

migrate:
  stage: migrate
  script:
    - docker run pgms-backend npm run migrate up -- -c 10
  only:
    - master
