stages:
  - build-image
  - stop-old-deploy
  - deploy
  - migrate

variables:
  PGMS_DOCKER_IMAGE_NAME: pgms-backend-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA

build-image:
  stage: build-image
  script:
    - docker build --no-cache -t $PGMS_DOCKER_IMAGE_NAME .
  only:
    - master
  
# test:
#   script:
#     - docker run -itd --rm pgms-backend:latest npm run test

delete-old-container:
  stage: stop-old-deploy
  script:
    - docker rm -f $PGMS_DOCKER_IMAGE_NAME || true
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker run -itd --restart=always -p 5001:5001 --name $PGMS_DOCKER_IMAGE_NAME $PGMS_DOCKER_IMAGE_NAME:latest
  only:
    - master

migrate:
  stage: migrate
  script:
    - docker run pgms-backend npm run migrate up -- -c 10
  only:
    - master
