stages:
  - build_image
  - test
  - deploy

build_image:
  script:
    - docker build -t pgms-backend .
  
test:
  script:
    - docker run -itd --rm pgms-backend:latest npm run test

deploy:
  script:
    - docker run -itd --restart=always -p 5001:5001 pgms-backend:latest
  only:
    - master
