stages:
  - build-image
  - stop-old-deploy
  - deploy

build-image:
  stage: build-image
  script:
    - docker build -t pgms-backend .
  
# test:
#   script:
#     - docker run -itd --rm pgms-backend:latest npm run test

delete-old-container:
  stage: stop-old-deploy
  script:
    - docker rm -f pgms-backend || true

deploy:
  stage: deploy
  script:
    - docker run -itd --restart=always -p 5001:5001 --name pgms-backend pgms-backend:latest
  only:
    - master
