stages:
  # - build-image
  # - stop-old-deploy
  # - deploy
  # - migrate
  - fix

# variables:
#   CONTIANER_NAME: pgms-backend
#   PGMS_DOCKER_IMAGE_NAME: pgms-backend-$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA

# build-image:
#   stage: build-image
#   script:
#     - docker build --no-cache -t $PGMS_DOCKER_IMAGE_NAME .
#   only:
#     - master

# delete-old-container:
#   stage: stop-old-deploy
#   script:
#     - docker rm -f $CONTIANER_NAME || true
#   only:
#     - master

# deploy:
#   stage: deploy
#   script:
#     - docker run -itd --restart=always -p 5001:5001 --name $CONTIANER_NAME $PGMS_DOCKER_IMAGE_NAME:latest
#   only:
#     - master

# migrate:
#   stage: migrate
#   script:
#     - docker run --rm $PGMS_DOCKER_IMAGE_NAME npm run migrate up -- -c 10
#   only:
#     - master

fix:
  stage: fix
  script:
    - docker network rm pgms-net
  only:
    - master
